version: '3.8'
services:
  homekit-code-generator:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: homekit-code-generator
    image: homekit-code-generator
    volumes:
      - ../:/app

